### ISSUE TITLE
Compatibility with SonarQube 6.5?

### ISSUE THREAD

**Issue by speze88** [JetBrains/TeamCity.SonarQubePlugin#30]
It seems the sonar teamcity plugin is not working with sonarqube 6.5. I presume this is because of the removal of ModuleFileSystem from the sonar API as stated in http://docs.sonarqube.org/display/SONAR/Release+6.1+Upgrade+Notes and https://jira.sonarsource.com/browse/SONAR-7864.

This is the exception thrown:
`Caused by: java.lang.NoClassDefFoundError: org/sonar/api/scan/filesystem/ModuleFileSystem
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getDeclaredConstructors(Class.java:2020)
        at org.picocontainer.injectors.ConstructorInjector$3.run(ConstructorInjector.java:403)
        at org.picocontainer.injectors.ConstructorInjector$3.run(ConstructorInjector.java:401)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.picocontainer.injectors.ConstructorInjector.getConstructors(ConstructorInjector.java:401)
        at org.picocontainer.injectors.ConstructorInjector.getSortedMatchingConstructors(ConstructorInjector.java:377)
        at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:128)
        at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
        at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
        at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
        at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
        at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
        at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
        at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
        at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:67)
        ... 80 more
Caused by: java.lang.ClassNotFoundException: org.sonar.api.scan.filesystem.ModuleFileSystem
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 100 more`

After rolling back to sonarqube 6.0 everything works fine. We've already tried to update the tc plugin, but it didn't change anything. We are using TC 9.1 (build 36973). 

Any ideas?

**Comment by Linfar** [comment]
@speze88 
TeamCity plugin doesn't use Sonar API at all. I think that this problem is caused by one of plugins installed in your SonarQube Server. Try to update them or disable one by one to find the broken. 
If it wont help - you can update bundled SonarQube Runner to the latest version

**Comment by Linfar** [comment]
Any update?

**Comment by speze88** [comment]
Sorry for the late reply. It was a plugin issue. After updating the plugins everything works fine. Anyway thanks for your help.

**Comment by brunojcm** [comment]
I think that SonarQube Cobertura plugin is not supported anymore and it doesn't work with current SonarQube (6.5).

**Comment by kkravikumar** [comment]
Yes, its not supported after SonarQube version 6.1+ more information https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix. Wish someone adds support in the newer versions.
